create table
  public.business (
    id bigint generated by default as identity,
    name text not null,
    address text not null,
    constraint business_pkey primary key (id)
  ) tablespace pg_default;


create table
  public.coupons (
    id integer generated by default as identity,
    name text not null,
    business_id bigint not null,
    cost integer not null,
    constraint coupons_pkey primary key (id),
    constraint coupons_business_id_fkey foreign key (business_id) references business (id)
  ) tablespace pg_default;


create table
  public.followers (
    id integer generated by default as identity,
    follower_id integer not null,
    date_added timestamp with time zone null,
    constraint Friendship_pkey primary key (id),
    constraint followers_id_fkey foreign key (id) references user_test (id) on delete cascade
  ) tablespace pg_default;


create table
  public.review (
    id integer generated by default as identity,
    author_name text not null,
    description text null,
    rating integer null,
    route_id integer null,
    user_id integer null,
    constraint review_pkey primary key (id),
    constraint review_route_id_fkey foreign key (route_id) references route (id),
    constraint review_user_id_fkey foreign key (user_id) references "user" (id)
  ) tablespace pg_default;


create table
  public.route (
    id integer generated by default as identity,
    name text not null,
    date_added timestamp with time zone null default now(),
    location text null,
    length_in_miles real null,
    difficulty integer null,
    activities text null,
    user_id integer null,
    coords real[] null,
    reported boolean not null default false,
    constraint Route_pkey primary key (id)
  ) tablespace pg_default;


  create table
  public.user_coupon_ledger (
    time timestamp with time zone not null default now(),
    user_id integer not null,
    coupon_id integer not null,
    change integer null,
    constraint user_coupon_ledger_pkey primary key (user_id, coupon_id),
    constraint user_coupon_ledger_coupon_id_fkey foreign key (coupon_id) references coupons (id)
  ) tablespace pg_default;


create table
  public.user_peepcoin_ledger (
    date timestamp with time zone not null default now(),
    user_id integer not null,
    change integer null,
    constraint user_peepcoin_ledger_pkey primary key (date, user_id)
  ) tablespace pg_default;


create table
  public.user_test (
    id integer generated by default as identity,
    date_joined timestamp with time zone not null default now(),
    username text null,
    num_followers integer not null default 0,
    constraint user_test_pkey primary key (id)
  ) tablespace pg_default;